### ISSUE TITLE
Handle a case when the deployment doesn't exist

### ISSUE THREAD

**Issue by wlk** [timoreimann/kubernetes-scripts#5]
Need to add a handler for a case when specific deployment doesn't exist (or there is error that has similar effect)

```
Waiting for deployment with timeout: 60 seconds
Error from server: deployments.extensions "test" not found
Waiting for specified generation:  for deployment test to be observed
Error from server: deployments.extensions "test" not found
```

My idea is that the script should wait for the deployment to be available.

**Comment by timoreimann** [comment]
My assumption so far was that the caller of the script must make sure that the deployment passed actually exists. Otherwise, we cannot know for sure if a given deployment is going to pop up any second or if we (the caller) passed in a wrong deployment name. Of course, we could add another timeout, but that would make things more complicated again.

Naturally, I am biased towards my own use cases. I'd be curious to know what kind of usage pattern you have that warrants waiting for a future deployment.

Side note: I noticed from your log that the script does not terminate on first error. PR #6 should have addressed that.

**Comment by wlk** [comment]
I think you are right on this, it doesn't make sense to add a timeout waiting for deployment to be created and it's better to fail quickly in this case, probably a large portion of when this happens is when someone makes a typo/mistake entering deployment name
